name: posix
version: 2.0.0-nullsafety.1
homepage: https://github.com/bsutton/dart_posix
description: Exposes the POSIX api on OSx and Linux
environment: 
  sdk: '>=2.12.0-0 <3.0.0'
dependencies: 
  ffi: ^1.0.0
dev_dependencies: 
  pedantic: ^1.10.0
  test: ^1.16.0
  ffigen: ^2.0.0
