name: dart_posix
description: Exposes the POSIX api on OSx and Linux
version: 0.0.1
homepage: https://github.com/bsutton/dart_posix

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ffi: 0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
